using System.Text.Json.Serialization;

namespace Ankh.Api.Objects;

/// <summary>
/// 
/// </summary>
public readonly record struct RoomObject(
    [property: JsonPropertyName("name")]
    string Name,
    [property: JsonPropertyName("description")]
    string Description,
    [property: JsonPropertyName("max_users")]
    long MaxUsers,
    [property: JsonPropertyName("permissions")]
    long Permissions,
    [property: JsonPropertyName("is_ap")]
    bool IsAp,
    [property: JsonPropertyName("is_vip")]
    bool IsVip,
    [property: JsonPropertyName("image_url")]
    Uri ImageUrl,
    [property: JsonPropertyName("url_token")]
    string UrlToken,
    [property: JsonPropertyName("language")]
    string Language,
    [property: JsonPropertyName("visitor_count")]
    long VisitorCount,
    [property: JsonPropertyName("is_non_guest_only")]
    bool IsNonGuestOnly,
    [property: JsonPropertyName("is_age_verified_only")]
    bool IsAgeVerifiedOnly,
    [property: JsonPropertyName("is_friends_only")]
    bool IsFriendsOnly,
    [property: JsonPropertyName("is_qa")]
    bool IsQa,
    [property: JsonPropertyName("whitelist_rating")]
    long WhitelistRating,
    [property: JsonPropertyName("experiences_id")]
    object ExperiencesId,
    [property: JsonPropertyName("mogile_key")]
    string MogileKey,
    [property: JsonPropertyName("mogile_domain")]
    string MogileDomain,
    [property: JsonPropertyName("expired")]
    object Expired,
    [property: JsonPropertyName("room_owners")]
    object[] RoomOwners,
    [property: JsonPropertyName("can_join_when_closed")]
    bool CanJoinWhenClosed,
    [property: JsonPropertyName("allow_room_shell_change")]
    bool AllowRoomShellChange,
    [property: JsonPropertyName("allow_ap_products")]
    bool AllowApProducts,
    [property: JsonPropertyName("room_shell_owner_id")]
    long RoomShellOwnerId,
    [property: JsonPropertyName("visitors_count")]
    long VisitorsCount,
    [property: JsonPropertyName("boot_count")]
    long BootCount,
    [property: JsonPropertyName("auto_innocent_count")]
    long AutoInnocentCount,
    [property: JsonPropertyName("is_grey_area")]
    bool IsGreyArea,
    [property: JsonPropertyName("is_greylisted")]
    bool IsGreylisted,
    [property: JsonPropertyName("last_modified")]
    DateTimeOffset LastModified,
    [property: JsonPropertyName("participants")]
    Dictionary<string, Participant> Participants,
    [property: JsonPropertyName("customers_avatar_name")]
    string CustomersAvatarName,
    [property: JsonPropertyName("room_download_size")]
    long RoomDownloadSize,
    [property: JsonPropertyName("rating")]
    double Rating,
    [property: JsonPropertyName("room_instance_id")]
    string RoomInstanceId,
    [property: JsonPropertyName("customers_id")]
    long CustomersId
);